apiVersion: v2
name: helm-charts-oci-proxy
description: Transparently proxy and transform Chart Repository styled Helm Charts as OCI artifacts. Now you can address any public Chart Repository styled Helm Chart as an OCI image.
type: application
version: 1.3.0
appVersion: "v1.0.0"
keywords:
  - Helm Proxy
  - OCI Proxy
  - Helm Chart Proxy
sources:
  - https://github.com/container-registry/helm-charts-oci-proxy
