name: "Publish Chart"
on:
  push:
    tags:
      - 'chart-*.*.*'
    branches:
      - main
jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - uses: azure/setup-helm@v5.0.0
        with:
          version: '4.1.4'
        id: install

      - name: Copy README.md to Chart Directory
        run: cp README.md chart/README.md

      - name: Create Chart Package
        run: helm package chart --version ${GITHUB_REF_NAME#chart-} --destination helm

      - name: Login to Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push Packaged Chart to Registry
        run: helm push helm/* oci://ghcr.io/${{ github.repository_owner }}/charts/helm-charts-oci-proxy
